### ISSUE TITLE
IOS devices

### ISSUE THREAD

**Issue by JR2012thman** [formatBCE/Format-BLE-Tracker#12]
I am an apple house hold and I have wanted to dual purpose my ESP devices and not have to run a dedicated ESP for ESPresence. Does this support IOS? Did I miss something in the read me?

**Comment by formatBCE** [comment]
Unfortunately it doesn't.

I plan to abandon this integration, and use Bermuda right now. Try it, it seems to be supporting iOS.

**Comment by JR2012thman** [comment]
Sounds good thanks for the heads up.

Very Respectfully,
Joshua Daniel Reid
