### ISSUE TITLE
NimBLEDevice.h: No such file or directory

### ISSUE THREAD

**Issue by swonge** [formatBCE/Format-BLE-Tracker#13]
When trying to use 0.07/0.0.8 version of Format-BLE-Tracker with suggested configuration to install in ESPHome (2024.8.1), the system prompted with the following error

Compiling .pioenvs/esp32-bluetooth-masterbedroom/src/esphome/components/esp32_ble_presense/esp32_ble_presense.o
Compiling .pioenvs/esp32-bluetooth-masterbedroom/src/esphome/components/esp32_ble_server/ble_2902.o
Compiling .pioenvs/esp32-bluetooth-masterbedroom/src/esphome/components/esp32_ble_server/ble_characteristic.o
Compiling .pioenvs/esp32-bluetooth-masterbedroom/src/esphome/components/esp32_ble_server/ble_descriptor.o
src/esphome/components/esp32_ble_presense/esp32_ble_presense.cpp:9:10: fatal error: NimBLEDevice.h: No such file or directory
**********************************************************************
* Looking for NimBLEDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:NimBLEDevice.h"
* Web  > https://registry.platformio.org/search?q=header:NimBLEDevice.h
*
**********************************************************************
 #include <NimBLEDevice.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esp32-bluetooth-masterbedroom/src/esphome/components/esp32_ble_presense/esp32_ble_presense.o] Error 1
========================= [FAILED] Took 21.49 seconds =========================

Any idea?

Thanks in advance

**Comment by formatBCE** [comment]
Framework ESP-IDF isn't supported currently.

Check Bermuda integration. It's really cool, well maintained and needs minimal configuration.
I abandoned this project and use Bermuda myself.
