### ISSUE TITLE
Status showing as Unknown

### ISSUE THREAD

**Issue by loryanstrant** [formatBCE/Format-BLE-Tracker#2]
I've only just re-installed this solution since it was updated for HA 2023.5, but it appears there may still be a bug somewhere as the room status is Unknown (despite my phone being right next to the base station):
![image](https://user-images.githubusercontent.com/51473494/236703445-cccc2587-c434-4b03-8fef-f518bb3e5d30.png)

As we can see however from the logic of the base station, it's definitely seeing my phone:
![image](https://user-images.githubusercontent.com/51473494/236703402-ed8ac495-88af-44b6-8cde-04f86ce04409.png)

And MQTT is also seeing the phone:
![image](https://user-images.githubusercontent.com/51473494/236703501-14ee201d-23ff-4afa-b103-713a7ff7af21.png)

**Comment by formatBCE** [comment]
Your minimal RSSI seems to be very high - it won't report room, if real RSSI is lower.

**Comment by formatBCE** [comment]
@loryanstrant hopefully you figured that out. Lower the Minimum RSSI to be -90 or some - and you will have the data. ESP does send them, so it's just matter of setting. Your exact RSSI was -88 there on screenshot, that's why it's ignored by integration (basically it says "beacon is too far from ESP, although visible").

**Comment by GMDD59** [comment]
Ich habe genau das gleiche Problem.
RSSI habe ich schon auf -99 eingestellt.
Egal welchen Namen ich dem Raum gebe, es wird nichts erkannt?
HA Core 2023.11.2

Wo könnte das Problem noch liegen?

**Comment by formatBCE** [comment]
> Ich habe genau das gleiche Problem.
> RSSI habe ich schon auf -99 eingestellt.
> Egal welchen Namen ich dem Raum gebe, es wird nichts erkannt?
> HA Core 2023.11.2
> 
> Wo könnte das Problem noch liegen?

Check your ESP logs - if it's sending data for your device. Maybe you entered wrong MAC/UUID? 

Also you can check that your devices are registered on MQTT server - under format_ble_tracker/alive you should see topic with your device's MAC/ID.
