### ISSUE TITLE
Do not see where to add new Bluetooth tag 

### ISSUE THREAD

**Issue by george2asenov** [formatBCE/Format-BLE-Tracker#3]
Hello,

I installed the integration and the ESP32 part also.
But from the readme I can't figure out where in home assistant should I add the device UUID to track

**Comment by formatBCE** [comment]
Just go to Settings - Devices & services and add new integration. Search Format BLE tracker there.

I thought it's obvious. :)

**Comment by george2asenov** [comment]
Thanks, figure out myself 2 minutes before you answer. Thanks again for the prompt response.

**Comment by formatBCE** [comment]
Np, good luck!
