### ISSUE TITLE
Never location "Skipping message with old timestamp"?

### ISSUE THREAD

**Issue by whitty** [formatBCE/Format-BLE-Tracker#7]
Hi,

Thanks for your work.  I apologise in advance in case this is a simple configuration problem as I'm a new user of your component (and first time user of MQTT - though long time user of H/A).

I've followed the instructions [from Alan - Home Automation Guy](https://www.homeautomationguy.io/blog/room-location-detection-with-format-ble-tracker-and-home-assistant) and cross-checked against the steps in [the readme](https://github.com/formatBCE/Format-BLE-Tracker).

Long Story Short - I've added two HA-app beacons and one mac-address beacon and I never see any presence updates for them.

I can see logs in the UART for the ESP32 that look like:

```
[D][format_ble:064][nimble_host]: Sending for 07D45F32-512D-XXXX-XXXX-XXXXXXXXXXXX
```

Enabling logging in `format_ble_tracker` shows this message `"Skipping message with old timestamp"` which seems to come from here.

https://github.com/formatBCE/Format-BLE-Tracker/blob/06d54764ae71e877de71d72b9edfc85998edc7db/custom_components/format_ble_tracker/__init__.py#L152

Enabling debug logging on yours and mqtt shows the up the following.

```
2024-07-22 11:47:24.328 DEBUG (MainThread) [homeassistant.components.mqtt.client] Mosquitto broker: register write 75
2024-07-22 11:47:24.329 DEBUG (MainThread) [homeassistant.components.mqtt.client] Mosquitto broker: unregister write 75
2024-07-22 11:47:43.761 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on format_ble_tracker/07D45F32-512D-XXXX-XXXX-XXXXXXXXXXXX/Living Room (qos=1): b'{"rssi":-78,"timestamp":0}'
2024-07-22 11:47:43.761 INFO (MainThread) [custom_components.format_ble_tracker] Skipping message with old timestamp
```

I assume the issue is related to timestamp == 0, though I'm not sure at what level that's coming from.

Let me know if there's any more relevant info I can give you.

Setup:

  * Home Assistant - x86_64 image
    - version 2024.7.3
    - supervisor 2024.06.2, 
    - OS 12.4
  * ESPHome
    * version 2024.7.0
    * ESP-WROOM-32

**Comment by formatBCE** [comment]
Hi! You're completely right on timestamp problem. Looks like your device has no time platform initialized. 
BTW, thank you for pointing to that how-to. I didn't knew that someone but me is actually using this code, not saying about writing how-tos on it. :)

To your problem: do you have that node connected to Home Assistant? I believe, in this case time on device is synchronized to time on Home Assistant, and everything works good. If not, then, I guess, any other way to provide ESP32 with correct local time would work. Like ESPHome `time:` integration, with NTP and stuff.

**Comment by whitty** [comment]
Thanks I fiddled through to the same conclusion myself, however I ran into compile issues with the `time` component interacting with your call to `time()`

See formatBCE/ESP32_BLE_presense#2

I originally tried `platform: sntp` and that did not work - not sure why - but `platform: homeassistant_time` resolved.

Additionally it resolved my followup issue which was the detection didn't seem to be very robust or responsive.  Something in  using the unresolvable time caused the detection to find nothing more than not (a 5 second scan where anything was heard was rare and the most back-to-back I'd ever seen was about one detection per minute).  That seems to be resolved now.

So I'm absolutely rapt with the results.

**Comment by formatBCE** [comment]
Probably, you have `pool.ntp.org` disabled somehow on your network?
Anyways, your PR is good! I just asked to add comments there. Thank you, and thanks for using this old code. :)

**Comment by whitty** [comment]
> Probably, you have pool.ntp.org disabled somehow on your network?

Shouldn't be, though these devices are on an IOT only network - and I did have at least one failure resolving the hassio node (the MQTT broker really), so its possible there's some transient behaviour and that would have worked.
